### ISSUE TITLE
`ModuleNotFoundError: No module named 'dataclasses'` error with  python3.6

### ISSUE THREAD

**Issue by eguchi1904** [Idein/actfw-core#44]
[dataclass are used in the source code](https://github.com/Idein/actfw-core/blob/ccd2890a7ff2c6b8fda4a382f2f94e9178b8dfb8/actfw_core/_private/schema/agent_app_protocol.py#L4). As a result, in the python3.6 environment, we got the above error unless install [dataclasses package](https://pypi.org/project/dataclasses/) separately.

**Comment by notogawa** [comment]
Do you mean [this line](https://github.com/Idein/actfw-core/blob/ccd2890a7ff2c6b8fda4a382f2f94e9178b8dfb8/pyproject.toml#L35) doesn't work? [CI setting](https://github.com/Idein/actfw-core/blob/ccd2890a7ff2c6b8fda4a382f2f94e9178b8dfb8/.circleci/config.yml#L4) includes tests in python 3.6 and [pass it](https://app.circleci.com/pipelines/github/Idein/actfw-core/514/workflows/2cd28ead-39ee-4676-8c9c-6de8fe6163e5/jobs/3492).

**Comment by eguchi1904** [comment]
Sorry, It's my mistake. I built and installed the package in python 3.8 environment and used it in 3.6 environment.
Thank you!
